site_name: Humber ITS Sites
nav:
  - 'index.md'
  - 'drupal-sites.md'
  - 'its-website.md'
  - 'cab-website.md'
theme:
  name: material
  logo: assets/humber-white-logo.svg
  favicon: assets/humber-favicon.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.path
    - toc.integrate  # Integrates the TOC into the side nav
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: indigo
      accent: light blue 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: indigo
      accent: light blue
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Humber-ITS
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
  - search
  - glightbox
copyright: |
  &copy; 2023 <a href="https://github.com/Humber-ITS"  target="_blank" rel="noopener">Humber College</a>